boku,
watashi,
hana/speak,
tabe/eat,
niku/meat,
han/half hour,
name/title,
mae/given name,
chuu/china,
naka/in or between,
sen/teacher,
gaku/as in student,
sei/as in student,
shuu/(shuushin),
shin/(shuushin),
hito or nin/person,
ni/as in japan,
hon/as in japan,
sakana/fish,
mizu/water,
ima/now,
ta as in tabe/eat,
han as in gohan/rice/meal,
no as in nomi/drink,
cha as in tea,
ya as in vegetables,
sai as in vegetables,
hana as in speak,
ta as in rice field,
ei as in England,
go as in nihongo/language,
nani/what,
gen as in genki,
ki as in genki,
ji as in hour or time,
one,
two,
three,
four,
five,
six,
seven,
eight,
nine,
ten,
